version: '3'

services:
  final-project:
    build:
      context: ./final-project
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://postgres:5432/jobs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  redis:
    image: bitnami/redis:latest
    networks:
      - app-network

  postgres:
    image: ubuntu/postgres
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  tester:
    build:
      context: ./final_project_tests
    depends_on:
      - final-project
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
